"""users table

Revision ID: 38739252b57c
Revises: 6be00b53f4d8
Create Date: 2023-06-02 20:41:10.489567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38739252b57c'
down_revision = '6be00b53f4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=False))
        batch_op.drop_index('ix_users_user_name')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_user_name', ['user_name'], unique=False)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
